name: Build Windows Executable

on:
  release:
    types: [created]
  workflow_dispatch:

env:
  LANG: en_US.UTF-8
  LC_ALL: en_US.UTF-8
  PYTHONUTF8: 1

permissions:
  contents: write  # Required repository permissions

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set Release Tag
      shell: powershell
      run: |
        $DATE = (Get-Date).ToString("yyyy-MM-dd")
        $VERSION = "v1"  # Version number, increment for each release
        $RELEASE_TAG = "$DATE-$VERSION"
        "RELEASE_TAG=$RELEASE_TAG" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
        pip install pyinstaller

    - name: Build executable
      shell: cmd
      run: |
        python -m PyInstaller --clean pdf_assistant.spec

        dir dist
        if exist "dist\PDF Reading Assistant" (
          dir "dist\PDF Reading Assistant"
          
          REM Copy executable files to dist root directory
          copy "dist\PDF Reading Assistant\PDF Reading Assistant (GUI).exe" dist\
          copy "dist\PDF Reading Assistant\PDF Reading Assistant (Web).exe" dist\
          
          REM Create ZIP package
          powershell "Compress-Archive -Path 'dist\PDF Reading Assistant\*' -DestinationPath 'dist\EnglishPDFAssistant_Windows.zip' -Force"
        ) else (
          echo Warning: Build directory not found
          dir dist
        )

    - name: Upload Release
      shell: powershell
      run: |
        gh release create "$env:RELEASE_TAG" `
          dist/EnglishPDFAssistant_Windows.zip `
          dist/"PDF Reading Assistant (GUI).exe" `
          dist/"PDF Reading Assistant (Web).exe" `
          --title "Release $env:RELEASE_TAG" `
          --notes "Windows Build Version $($env:RELEASE_TAG)"
          
      env:
        GH_TOKEN: ${{ github.token }} 