name: Build Android APK

on:
  release:
    types: [created]
  workflow_dispatch:

env:
  LANG: zh_CN.UTF-8
  LC_ALL: zh_CN.UTF-8
  PYTHONUTF8: 1

permissions:
  contents: write  # 必须的仓库权限

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set Release Tag
      shell: bash
      run: |
        DATE=$(date +%Y-%m-%d)
        VERSION="v1"  # 版本号，每次发布时递增
        RELEASE_TAG="$DATE-$VERSION"
        echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install buildozer cython kivy

    - name: Setup environment
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config \
          zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
        sudo apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
          libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev
        sudo apt-get install -y lld

    - name: Setup Android SDK
      run: |
        mkdir -p ~/.android
        echo 'count=0' > ~/.android/repositories.cfg
        
        # 接受许可
        echo y | buildozer android update

    - name: Build APK
      run: |
        buildozer android debug
        
        # 重命名APK文件以包含版本标签
        mv bin/pdfassistant-*-debug.apk bin/PDFAssistant-${{ env.RELEASE_TAG }}.apk

    - name: Upload to Release
      shell: bash
      run: |
        gh release create "$RELEASE_TAG" \
          bin/PDFAssistant-${{ env.RELEASE_TAG }}.apk \
          --title "PDF阅读助手 $RELEASE_TAG" \
          --notes "Android版本PDF阅读助手 $RELEASE_TAG

          ## 功能特点

          - 文本提取：支持多种提取方法
          - 智能翻译：多种翻译引擎支持
          - 词汇分析：自动提取重要单词并解释
          - 移动端优化：更适合在手机上使用

          ## 安装方法

          1. 下载APK文件
          2. 在Android设备上安装APK
          3. 授予存储权限
          4. 打开应用并开始使用

          ## 注意事项

          - 首次运行需要联网下载语言模型
          - 需要配置API密钥
          "
      env:
        GH_TOKEN: ${{ github.token }}  # 使用GitHub自动生成的token 